"""create info users

Revision ID: 7b6eb06761c0
Revises: 877a11d47907
Create Date: 2025-05-30 16:58:24.054677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b6eb06761c0'
down_revision: Union[str, None] = '877a11d47907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expenses', 'identificador',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('revenues', 'identificador',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('revenues', 'identificador',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('expenses', 'identificador',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
