"""add identificador to revenue and expense

Revision ID: 877a11d47907
Revises: bcf1e33973ec
Create Date: 2025-05-30 13:20:05.470000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '877a11d47907'
down_revision: Union[str, None] = 'bcf1e33973ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    with op.batch_alter_table('expenses') as batch_op:
        batch_op.add_column(sa.Column('identificador', sa.String(), nullable=True))
        batch_op.create_unique_constraint('uq_expenses_identificador', ['identificador'])

    with op.batch_alter_table('revenues') as batch_op:
        batch_op.add_column(sa.Column('identificador', sa.String(), nullable=True))
        batch_op.create_unique_constraint('uq_revenues_identificador', ['identificador'])

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'revenues', type_='unique')
    op.drop_column('revenues', 'identificador')
    op.drop_constraint(None, 'expenses', type_='unique')
    op.drop_column('expenses', 'identificador')
    # ### end Alembic commands ###
