"""create tag gols

Revision ID: e2a92146a1cf
Revises: 90a3aab6765c
Create Date: 2025-06-02 03:37:07.077384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2a92146a1cf'
down_revision: Union[str, None] = '90a3aab6765c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('type', sa.String(
        length=50), nullable=False, server_default='despesa'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'type')
    # ### end Alembic commands ###
